# Stage 1: Build
FROM node:16 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./src ./src
COPY tsconfig.json tsconfig.json

RUN apt-get update && apt-get install bash

RUN npx prisma generate --schema src/database/prisma/schema.prisma

RUN npm run build

# Stage 2: Run
FROM node:16-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3001

CMD ["node", "dist/api/server.js"]
