version: '3.9'

services:
  ng-bank-db-test:
    image: postgres:latest
    container_name: ng-bank-db-test
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=12345678
    restart: 'always'
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

  ng-bank-backend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      ng-bank-db-test:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - DATABASE_URL_TEST=postgresql://postgres:12345678@ng-bank-db-test:5432/ng-bank-test-docker?schema=public
      - JWT_SECRET=dsadsadas92je93ms02ms02new
