FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

EXPOSE 3001

COPY . .

RUN apt-get update && apt-get install bash

RUN apt-get update && apt-get install -y curl

RUN npx prisma generate --schema src/database/prisma/schema.prisma
